[Plugin] Serve plugin for Denopack
denofn/denopack pull request #15
Opened 2020-08-23 07:05 UTC by Soremwar

Works as expected, couple reworks I wanna do before this is landed

### TODO
- [x] Add support for https server
- [x] (If possible) refactor options so they are not a complete mess to handle internally
- [x] Add documentation

To test it, just import and use the plugin. You can pass either a string(s) or an options object to start it

2020-08-23 17:31 UTC, Soremwar commented
@jeroenptrs All set!

2020-08-24 22:16 UTC, jeroenptrs requested changes
I'd prefer if the plugin name was a bit more in line with the rest of the plugins. After that we can merge this in, since it's looking really good 😄

2020-08-24 22:16 UTC, jeroenptrs commented on plugin/serve/mod.ts
> +export const serve = (
```diff
- export const serve = {
+ export const pluginServe = {
```

2020-08-24 22:16 UTC, jeroenptrs commented on plugin/serve/mod.ts
> +    name: "serve",
```diff
- name: "serve"
+ name: "denopack-plugin-serve"
```

2020-08-25 07:15 UTC, jeroenptrs approved these changes
LGTM! 🎉

2020-08-25 07:15 UTC, merged